### ISSUE TITLE
Node ReferenceError: X2JS is not defined ??

### ISSUE THREAD

**Issue by vaughanc-zz** [abdmob/x2js#46]
Hi, not sure if I'm doing something wrong here but I'm getting the following issue "ReferenceError: X2JS is not defined".  Any help would be greatly appreciated.

Thanks

server:test chris$ cat package.json
{
  "name"    : "myapp",
  "version" : "0.0.1",
  "main"    : "main.js",
  "dependencies": {
    "x2js": "^3.1.0"
  }
}

server:test chris$ npm install x2js
myapp@0.0.1 /Users/chris/scripts/tapps_proj/test
└── x2js@3.1.0

npm WARN myapp@0.0.1 No description
npm WARN myapp@0.0.1 No repository field.
npm WARN myapp@0.0.1 No license field.
server:test chris$ node main.js
/Users/chris/scripts/tapps_proj/test/main.js:4
var x2js = new X2JS();
               ^

ReferenceError: X2JS is not defined
    at Object.<anonymous> (/Users/chris/scripts/tapps_proj/test/main.js:4:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
server:test chris$ cat main.js
require('x2js');

// Create x2js instance with default config
var x2js = new X2JS();
var xmlText = "<MyRoot><test>Success</test><test2><item>val1</item><item>val2</item></test2></MyRoot>";
var jsonObj = x2js.xml_str2json( xmlText );

**Comment by IrynaBu** [comment]
+1

**Comment by remmel** [comment]
npm package x2js is another lib, it looks like you should use `npm i x2js-fork`
